SUPER_CONFIG_PATH: ./configs/r50_deformable_detr_motip_dancetrack.yaml

DETR_FRAMEWORK: DAB-Deformable-DETR
DETR_PRETRAIN: ./pretrains/r50_dab_deformable_detr_coco_dancetrack.pth

# Different dimension settings for DAB DETR:
DETR_HIDDEN_DIM: 256
DETR_DIM_FEEDFORWARD: 2048
SEQ_HIDDEN_DIM: 256
SEQ_DIM_FEEDFORWARD: 1024

# From DAB DETR training settings:
DETR_CLS_LOSS_COEF: 1.0
DETR_SET_COST_CLASS: 2.0

# Larger image size, align with previous researches, like MOTR, MeMOTR, etc.
AUG_RESIZE_SCALES: [608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992]
AUG_MAX_SIZE: 1536
AUG_RANDOM_RESIZE: [800, 1000, 1200]
AUG_RANDOM_CROP_MIN: 800
AUG_RANDOM_CROP_MAX: 1200
INFERENCE_MAX_SIZE: 1536